blogsite/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.MainPage.as_view(), name='main_page'),
    path('all_posts/', views.ShowAllPosts.as_view(), name='show_all_posts'),
    path('draft_posts/', views.ShowAllPosts.as_view(draft=True), name='show_draft_posts'),
    path('saved_posts/', views.ShowAllPosts.as_view(reacted="saved"), name='show_saved_posts'),
    path('liked_posts/', views.ShowAllPosts.as_view(reacted="liked"), name='show_liked_posts'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='show_post'),
    path('post/draft/<slug:post_slug>/', views.ShowPost.as_view(draft=True), name='show_draft_post'),
    path('posts_by_theme/<slug:theme_slug>/', views.ShowPostsByTheme.as_view(), name='show_posts_by_theme'),

    path('themes/', views.ShowThemes.as_view(), name='themes'),
    path('redact_theme/<slug:theme_slug>/', views.RedactTheme.as_view(), name='redact_theme'),
    path('create_theme/', views.CreateTheme.as_view(), name='create_theme'),
    path('delete_theme/<slug:theme_slug>/', views.DeleteTheme.as_view(), name='delete_theme'),

    path('create_post/', views.CreatePost.as_view(), name='create_post'),
    path('delete_post/<slug:post_slug>/', views.DeletePost.as_view(), name='delete_post'),
    path('post/<slug:post_slug>/redact/', views.RedactPost.as_view(), name='redact_post'),
    path('my_post/<slug:post_slug>/redact/', views.RedactMyPost.as_view(), name='redact_my_post'),

    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('dislike_post/<int:post_id>/', views.dislike_post, name='dislike_post'),
    path('save_post/<int:post_id>/', views.make_save_post, name='save_post'),

    path('api/posts/', views.PostsAPI.as_view(), name='posts_api'),
    path('api/draft_posts/', views.PostsAPI.as_view(draft=True), name='draft_posts_api'),
    path('api/liked_posts/', views.PostsAPI.as_view(reacted='liked'), name='liked_posts_api'),
    path('api/saved_posts/', views.PostsAPI.as_view(reacted='saved'), name='save_posts_api'),

    path('api/post/<int:post_id>/', views.PostAPI.as_view(), name='post_api'),
    path('api/draft_post/<int:post_id>/', views.PostAPI.as_view(draft=True), name='drraft_post_api'),
    path('api/posts/<slug:theme_slug>/', views.PostsByThemeAPI.as_view(), name='posts_by_theme_api'),

    path('api/themes/', views.ThemesAPI.as_view(), name='themes_api'),
    path('api/theme/<slug:theme_slug>/', views.ThemeAPI.as_view(), name='theme_api'),
]

blogsite/blogsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blogsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include('users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Адмін панель"
admin.site.index_title = "Sonwayr`s blog"

blogsite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.RegistrateUser.as_view(), name='registration'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:profile_pk>/', views.ShowProfile.as_view(), name='profile'),
    path('redact_profile/', views.RedactProfile.as_view(), name='redact_profile'),
    path('subscribe/<int:user_id>/', views.subscribe, name='subscribe'),
    path('subscribes/', views.ShowSubscribes.as_view(), name='show_subscribes'),
]

blogsite/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/%m/%d', verbose_name='Фото', blank=True, null=True)
    date_birth = models.DateTimeField(blank=True, null=True,
                                      verbose_name='Дата народження')

    subscribes = models.ManyToManyField('self', blank=True, symmetrical=False,
                                        default=None, verbose_name='Підписки')

    subscribers = models.IntegerField(blank=True, default=0, verbose_name='Підписники')

    liked_post = models.ManyToManyField('blog.Post', blank=True, default=None,
                                        related_name='liked_post', verbose_name='Лайкнуті')
    disliked_post = models.ManyToManyField('blog.Post', blank=True, default=None,
                                           related_name='disliked_post', verbose_name='Дізлайкнуті')
    saved_post = models.ManyToManyField('blog.Post', blank=True, default=None,
                                        related_name='saved_post', verbose_name='Збережені')

    class Meta:
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return f"{self.first_name} {self.last_name}({self.username})"

blogsite/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
import datetime

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import Permission


class RegistrateUserForm(UserCreationForm):
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(attrs={'class': 'form-control'},
                                                               years=tuple(range(this_year - 100, this_year - 5))))

    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор паролю', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = [
            'first_name', 'last_name', 'email', 'username', 'password1', 'password2',
            'photo', 'date_birth'
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такий E-mail вже зайнят!")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()
        add_post_permission = Permission.objects.get(codename='add_post')
        user.user_permissions.add(add_post_permission)

        return user


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(
        attrs={"class": 'form-control'})
                               )

    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}
    ))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RedactProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'photo']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

blogsite/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, F
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from blog.models import Post
from users.forms import RegistrateUserForm, LoginUserForm, RedactProfileForm


# Create your views here.
class RegistrateUser(CreateView):
    form_class = RegistrateUserForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('main_page')
    extra_context = {'title': 'Реєстрація', 'btn_name': 'Зареєструватись'}


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/registration.html'
    extra_context = {'title': 'Авторизація', 'btn_name': 'Авторизуватись'}


class ShowProfile(LoginRequiredMixin, DetailView):
    model = get_user_model()  # User
    template_name = 'users/profile.html'
    pk_url_kwarg = 'profile_pk'
    context_object_name = 'profile'
    extra_context = {'title': 'Профіль'}
    paginate_by = 10  # Устанавливает количество постов на странице

    def get_object(self, queryset=None):
        queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.kwargs.get('profile_pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Post.active.select_related('theme', 'author').filter(author=self.kwargs.get('profile_pk'))

        paginator = Paginator(posts, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        context['page_obj'] = paginator.get_page(page)
        context['posts'] = posts
        return context


class RedactProfile(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = RedactProfileForm
    template_name = 'blog/create_theme.html'
    extra_context = {'title': 'Редагування профілю', 'btn_name': 'Зберегти'}

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'profile_pk': self.request.user.pk})

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def subscribe(request, user_id):
    user = request.user
    user_to_subscribe = get_object_or_404(get_user_model(), pk=user_id)
    if user_to_subscribe != user:
        if not user.subscribes.filter(pk=user_to_subscribe.pk).exists():
            user.subscribes.add(user_to_subscribe)
            user_to_subscribe.subscribers = F('subscribers') + 1
        else:
            user.subscribes.remove(user_to_subscribe)
            user_to_subscribe.subscribers = F('subscribers') - 1
        user.save()
        user_to_subscribe.save()
    return redirect(request.META.get('HTTP_REFERER', '/'))


class ShowSubscribes(LoginRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'users/subscribes.html'
    context_object_name = 'subscribes'
    paginate_by = 10
    extra_context = {'title': 'Підписки'}

    def get_queryset(self):
        return self.request.user.subscribes.all()

blogsite/users/templates/users/profile.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}

{% show_info title %}

{% endblock %}

{% block content %}

<section id="service">
    <div class="container">
        <div class="single-item text-center">
            <h1 class="post-h">{{profile}}</h1>
            <div class="profile-info">
                <div class='home-text-profile'>

                    <h4 class="post-h">Імя: {{profile.first_name}} {{ profile.last_name}}</h4>
                    <h4 class="post-h">Нікнейм: {{profile.username}}</h4>

                </div>

                {% if profile.photo %}
                <div class='home-text-profile text-center'>
                    <img src="{{profile.photo.url}}">
                </div>
                {% else %}
                <img src="#">
                {% endif %}
                <div class="home-text-profile">

                    {% if profile.pk == request.user.pk %}
                    <h4 class="post-h">Підписників: {{profile.subscribers}}</h4>
                    <h4 class="post-h"><a href="{% url 'show_liked_posts' %}" class="red-btn">Лайкнуті</a></h4>
                    <h4 class="post-h"><a href="{% url 'show_saved_posts' %}" class="red-btn">Збережені</a></h4>
                    <h4 class="post-h"><a href="{% url 'users:show_subscribes' %}" class="red-btn">Підписки</a></h4>
                    <h4><a href="{% url 'users:redact_profile' %}" class="red-btn">Відредагувати профіль</a></h4>
                    {% else %}
                    <h4 class="post-h">Підписників: <a href="{% url 'users:subscribe' profile.pk %}">{{profile.subscribers}}</a></h4>

                    {% endif %}
                </div>

            </div>

        </div>

    </div>
    <div class="container">
        <div class="home-text text-center">
            <h4>Пости від цього користувача</h4>
        </div>
        {% for post in posts %}
        {% show_post_tag post a_lot=True draft=draft %}
        {% endfor %}

    </div>
</section>

{% endblock %}
{% block navigation %}
{% paginate page_obj %}
{% endblock %}

blogsite/users/templates/users/registration.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}

{% show_info title %}

{% endblock %}
{% block content %}
<section id="contact">
    {% if not user.is_authenticated %}

    {% show_form form btn_name %}

    {% else %}
    <div class="text-center">
        <h1 class="home-text text-center">Ви вже авторизовані</h1>
        <h1><a href="{% url 'main_page' %}" class="red-btn">На головну</a>
        </h1>
    </div>
    {% endif %}
</section>
{% endblock %}

blogsite/users/templates/users/subscribes.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
{% show_info title %}
{% endblock %}

{% block content %}
<section id="service">
    <div class="container">
        {% for profile in subscribes %}
        <div class="single-item text-center">
            <h1 class="post-h">{{profile}}</h1>
            <div class="profile-info">
                <div class='home-text-profile'>

                    <h4 class="post-h">Імя: {{profile.first_name}} {{ profile.last_name}}</h4>
                    <h4 class="post-h">Нікнейм: {{profile.username}}</h4>

                </div>

                {% if profile.photo %}
                <div class='home-text-profile text-center'>
                    <img src="{{profile.photo.url}}">
                </div>
                {% else %}
                <img src="#">
                {% endif %}
                <div class="home-text-profile">


                    <h4 class="post-h">Підписників: <a href="{% url 'users:subscribe' profile.pk %}">{{profile.subscribers}}</a>
                    </h4>


                </div>

            </div>

        </div>
        {% endfor %}
    </div>

</section>
{% endblock %}