blogsite/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.MainPage.as_view(), name='main_page'),
    path('all_posts/', views.ShowAllPosts.as_view(), name='show_all_posts'),
    path('draft_posts/', views.ShowAllPosts.as_view(draft=True), name='show_draft_posts'),
    path('saved_posts/', views.ShowAllPosts.as_view(reacted="saved"), name='show_saved_posts'),
    path('liked_posts/', views.ShowAllPosts.as_view(reacted="liked"), name='show_liked_posts'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='show_post'),
    path('post/draft/<slug:post_slug>/', views.ShowPost.as_view(draft=True), name='show_draft_post'),
    path('posts_by_theme/<slug:theme_slug>/', views.ShowPostsByTheme.as_view(), name='show_posts_by_theme'),

    path('themes/', views.ShowThemes.as_view(), name='themes'),
    path('redact_theme/<slug:theme_slug>/', views.RedactTheme.as_view(), name='redact_theme'),
    path('create_theme/', views.CreateTheme.as_view(), name='create_theme'),
    path('delete_theme/<slug:theme_slug>/', views.DeleteTheme.as_view(), name='delete_theme'),

    path('create_post/', views.CreatePost.as_view(), name='create_post'),
    path('delete_post/<slug:post_slug>/', views.DeletePost.as_view(), name='delete_post'),
    path('post/<slug:post_slug>/redact/', views.RedactPost.as_view(), name='redact_post'),
    path('my_post/<slug:post_slug>/redact/', views.RedactMyPost.as_view(), name='redact_my_post'),

    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('dislike_post/<int:post_id>/', views.dislike_post, name='dislike_post'),
    path('save_post/<int:post_id>/', views.make_save_post, name='save_post'),

    path('api/posts/', views.PostsAPI.as_view(), name='posts_api'),
    path('api/draft_posts/', views.PostsAPI.as_view(draft=True), name='draft_posts_api'),
    path('api/liked_posts/', views.PostsAPI.as_view(reacted='liked'), name='liked_posts_api'),
    path('api/saved_posts/', views.PostsAPI.as_view(reacted='saved'), name='save_posts_api'),

    path('api/post/<int:post_id>/', views.PostAPI.as_view(), name='post_api'),
    path('api/draft_post/<int:post_id>/', views.PostAPI.as_view(draft=True), name='drraft_post_api'),
    path('api/posts/<slug:theme_slug>/', views.PostsByThemeAPI.as_view(), name='posts_by_theme_api'),

    path('api/themes/', views.ThemesAPI.as_view(), name='themes_api'),
    path('api/theme/<slug:theme_slug>/', views.ThemeAPI.as_view(), name='theme_api'),
]

blogsite/blogsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blogsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include('users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Адмін панель"
admin.site.index_title = "Sonwayr`s blog"

blogsite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.RegistrateUser.as_view(), name='registration'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:profile_pk>/', views.ShowProfile.as_view(), name='profile'),
    path('redact_profile/', views.RedactProfile.as_view(), name='redact_profile'),
    path('subscribe/<int:user_id>/', views.subscribe, name='subscribe'),
    path('subscribes/', views.ShowSubscribes.as_view(), name='show_subscribes'),
]

blogsite/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
import transliterate
from django.urls import reverse
from django.utils.text import slugify

from blogsite.settings import DEFAULT_THEME_SLUG


class ActivePostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=Post.Status.ACTIVE)


class DraftPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=Post.Status.DRAFT)


class Theme(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name='Назва теми')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='Слаг')

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Теми'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('show_posts_by_theme', kwargs={'theme_slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = transliterate.slugify(self.name)
        super().save(*args, **kwargs)


def get_default_theme():
    return Theme.objects.get(slug=DEFAULT_THEME_SLUG)


# Create your models here.
class Post(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Чернетка'
        ACTIVE = 1, 'Опублікований'

    title = models.CharField(max_length=255, verbose_name='Назва', unique=True)

    slug = models.SlugField(max_length=255, unique=True, db_index=True,
                            verbose_name='Слаг')

    content = models.TextField(verbose_name='Зміст поста')

    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default=None, blank=True,
                              null=True, verbose_name='Фото')

    time_create = models.DateTimeField(auto_now_add=True,
                                       verbose_name='Час створення')

    theme = models.ForeignKey('Theme', on_delete=models.SET_DEFAULT, default=get_default_theme,
                              related_name='theme', verbose_name='Тема')

    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True,
                               related_name='Власник')

    is_active = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                    default=Status.DRAFT, verbose_name='Статус')

    liked = models.IntegerField(default=0, blank=True, verbose_name='Кількість лайків')
    disliked = models.IntegerField(default=0, blank=True, verbose_name='Кількість дизлайків')
    saved = models.IntegerField(default=0, blank=True, verbose_name='Кількість збережень')

    objects = models.Manager()
    active = ActivePostManager()
    draft = DraftPostManager()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        ordering = ['time_create']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('show_post', kwargs={'post_slug': self.slug})

    def save(self, *args, **kwargs):
        if self.title:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

blogsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link type="text/css" href="{% static 'blog/css/style.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'blog/css/font-awesome.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'blog/css/prettyPhoto.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'blog/css/responsive.css' %}" rel="stylesheet"/>


    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="smooth-scroll"><a href="{% url 'main_page' %}">Головна</a></li>
                    <li class="smooth-scroll"><a href="{% url 'show_all_posts' %}">Пости</a></li>
                    {% if perms.blog.change_post %}
                    <li class="smooth-scroll"><a href="{% url 'show_draft_posts' %}">Чернетки</a></li>
                    {% endif %}
                    <li class="smooth-scroll"><a href="{% url 'themes' %}">Теми</a></li>
                    {% if perms.blog.add_theme %}
                    <li class="smooth-scroll"><a href="{% url 'create_theme' %}">Створити тему</a></li>
                    {% endif %}
                    {% if perms.blog.add_post %}
                    <li class="smooth-scroll"><a href="{% url 'create_post' %}">Створити пост</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="smooth-scroll"><a href="{% url 'users:profile' user.pk %}">{{ user.username }}</a></li>
                    <li class="smooth-scroll"><a href="{% url 'users:logout' %}">Вийти</a></li>
                    {% else %}
                    <li class="smooth-scroll"><a href="{% url 'users:login' %}">Увійти</a></li>
                    <li class="smooth-scroll"><a href="{% url 'users:registration' %}">Зареєструватися</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
</header>

<!--Home Section-->
{% block main %}
<!--<div class="overlay"></div>-->
{% endblock %}

<!--SERVICES AREA-->
{% block info %}
<!--	<div class="container">-->
<!--		<div class="row">-->
<!--			<div class="col-md-12  wow bounce">-->
<!--				<div class="section-heading text-center text-uppercase  wow bounceInUp">-->
<!--					<h2>OUR <span>SERVICeS</span></h2>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	<div class="container">-->
<!--		<div class="row">-->
<!--			<div class="col-sm-6 col-md-3  wow bounceIn">-->
<!--				<div class="single-item text-center">-->
<!--					<i class="fa fa-laptop"></i>-->
<!--					<h4 class="text-uppercase">Responsive Design</h4>-->

<!--					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.</p>-->
<!--					<a href="#" class="btn btn-red text-uppercase">more</a>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
{% endblock %}
<!--team section-->
{% block content %}

{% endblock %}

{% block navigation %}

{% endblock %}
<!--contact heading-->
{% block contact %}

{% endblock %}
<!-- footer-area-->
<footer>
    <div class="container">
        <div class="row">

            <div class="col-sm-8">
                <div class="footer-p text-center">
                    <p>Sonwayr`s site</p>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="footer-social text-center">
                    <a href="#"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="js/jquery-1.11.3.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/isotope.2.2.2min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script src="js/wow.min.js"></script>
<script src="js/jquery.prettyPhoto.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="js/main.js"></script>
</body>
</html>

blogsite/templates/pagination.html
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
        {% if page_obj.has_previous %}
        <li class="page-num">
            <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        </li>
        {% endif %}
        {% for p in page_obj.paginator.page_range %}

        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:+2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-num">
            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}